### ISSUE TITLE
It is possible all the graphql operations(query,mutation and subscription) via websocket transport fully?

### ISSUE THREAD

**Issue by developerworks** [graphql-java/graphql-java-subscription-example#2]
I kown this project: https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport which support fully websocket transport in both server and client side.

I want to build a real-time web application based on graphql with java. Is there examples of this ?

**Comment by bbakerman** [comment]
Yes there is - this one.  This example is a client and server example of using websockets to provide realtime updates to data.

The challenge for you is have a realtime backing store (which is not covered here) but you can take a lot of this code as a basis for a java WebSocket based app.

See https://github.com/graphql-java/graphql-java-subscription-example/blob/master/src/main/java/com/graphql/example/http/StockTickerWebSocket.java for the gory details

Plus the JS for the client side WS code
